## Analysis on CarDekho Dataset

In [3]:
# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [54]:
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

In [41]:
df = pd.read_csv('./Car details v3.csv')
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0

In [42]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'torque',
       'seats'],
      dtype='object')

In this dataset we look to predict the selling_price based on the various measures and factors provided. We will try to fit a model which helps us to do the same.

In [43]:
df.isna().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [44]:
df=df.dropna()

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7906 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           7906 non-null   object
 1   year           7906 non-null   int64
 2   selling_price  7906 non-null   int64
 3   km_driven      7906 non-null   int64
 4   fuel           7906 non-null   object
 5   seller_type    7906 non-null   object
 6   transmission   7906 non-null   object
 7   owner          7906 non-null   object
 8   mileage        7906 non-null   object
 9   engine         7906 non-null   object
 10  max_power      7906 non-null   object
 11  torque         7906 non-null   object
 12  seats          7906 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 864.7+ KB

In [46]:
df['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [47]:
df = pd.concat([df.drop('fuel',axis=1),pd.get_dummies(df.fuel)],axis=1)

In [48]:
df.sample(5)

,name,year,selling_price,km_driven,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,CNG,Diesel,LPG,Petrol
7123,Ford Ecosport 1.5 Diesel Trend,2014,570000,48000,Individual,Manual,First Owner,21.7 kmpl,1498 CC,98.96 bhp,215Nm@ 1750-2500rpm,5.0,0,1,0,0
654,Honda Jazz VX,2016,550000,56494,Trustmark Dealer,Manual,First Owner,18.2 kmpl,1199 CC,88.7 bhp,110Nm@ 4800rpm,5.0,0,0,0,1
3284,Hyundai Grand i10 1.2 Kappa Sportz Dual Tone,2019,640000,10000,Individual,Manual,First Owner,18.9 kmpl,1197 CC,81.86 bhp,113.75nm@ 4000rpm,5.0,0,0,0,1
2572,Maruti Alto K10 VXI,2017,320000,32000,Individual,Manual,Second Owner,23.95 kmpl,998 CC,67.05 bhp,90Nm@ 3500rpm,5.0,0,0,0,1
7083,Toyota Etios G,2013,350000,100000,Individual,Manual,Second Owner,16.78 kmpl,1496 CC,88.73 bhp,132Nm@ 3000rpm,5.0,0,0,0,1

In [59]:
# Checking for the significance of fuel type
m_fuel = ols('selling_price ~ CNG + Petrol + LPG + Diesel',data=df).fit()
print(m_fuel.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          selling_price   R-squared:                       0.043
Model:                            OLS   Adj. R-squared:                  0.042
Method:                 Least Squares   F-statistic:                     87.91
Date:                Thu, 16 Nov 2023   Prob (F-statistic):           3.33e-73
Time:                        16:11:38   Log-Likelihood:            -1.1864e+05
No. Observations:                7906   AIC:                         2.373e+05
Df Residuals:                    7901   BIC:                         2.373e+05
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -2.98e+17   6.38e+17     -0.467      0.641   -1.55e+18    9.53e+17
CNG          2.98e+17   6.38e+17      0.467      0.641   -9.53e+17    1.55e+18
Petrol       2.98e+17   6.38e+17      0.467      0.641   -9.53e+17    1.55e+18
LPG          2.98e+17   6.38e+17      0.467      0.641   -9.53e+17    1.55e+18
Diesel       2.98e+17   6.38e+17      0.467      0.641   -9.53e+17    1.55e+18
==============================================================================
Omnibus:                     6843.957   Durbin-Watson:                   1.146
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           177862.812
Skew:                           4.218   Prob(JB):                         0.00
Kurtosis:                      24.651   Cond. No.                     1.95e+14
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.11e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [60]:
m_fuel = ols('selling_price ~ CNG + Petrol + LPG',data=df).fit()
print(m_fuel.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          selling_price   R-squared:                       0.043
Model:                            OLS   Adj. R-squared:                  0.042
Method:                 Least Squares   F-statistic:                     117.3
Date:                Thu, 16 Nov 2023   Prob (F-statistic):           2.52e-74
Time:                        16:14:47   Log-Likelihood:            -1.1864e+05
No. Observations:                7906   AIC:                         2.373e+05
Df Residuals:                    7902   BIC:                         2.373e+05
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   8.025e+05   1.21e+04     66.081      0.000    7.79e+05    8.26e+05
CNG        -4.845e+05   1.11e+05     -4.362      0.000   -7.02e+05   -2.67e+05
Petrol     -3.298e+05   1.81e+04    -18.222      0.000   -3.65e+05   -2.94e+05
LPG        -5.916e+05   1.35e+05     -4.378      0.000   -8.56e+05   -3.27e+05
==============================================================================
Omnibus:                     6838.473   Durbin-Watson:                   1.146
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           177549.699
Skew:                           4.213   Prob(JB):                         0.00
Kurtosis:                      24.633   Cond. No.                         16.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

**Interpretation** :

Here we see that when we take only three of the fuel types we see they all are insignificant in the presence of other, but when we take all four of them we see a increse in the p values of all of them. We see them become insignificant because we know that, 

CNG + LPG + Petrol + Diesel = 1(always).

Also we see that they are negatively correlated with the price.

In [49]:
df.seller_type.unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [51]:
df = pd.concat([df.drop('seller_type',axis=1),pd.get_dummies(df.seller_type)],axis=1)

In [52]:
df.head(5)

,name,year,selling_price,km_driven,transmission,owner,mileage,engine,max_power,torque,seats,CNG,Diesel,LPG,Petrol,Dealer,Individual,Trustmark Dealer
0,Maruti Swift Dzire VDI,2014,450000,145500,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,0,1,0,0,0,1,0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,0,1,0,0,0,1,0
2,Honda City 2017-2020 EXi,2006,158000,140000,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,0,0,0,1,0,1,0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,0,1,0,0,0,1,0
4,Maruti Swift VXI BSIII,2007,130000,120000,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,0,0,0,1,0,1,0